/**
 * Curated descriptions of cBioPortal page tabs, used in tool responses
 * to give the LLM accurate context about what each tab shows.
 *
 * These are sourced from the cBioPortal frontend and documentation —
 * NOT generated by the LLM. The LLM is instructed to use this field
 * verbatim and not to supplement it with training-data knowledge.
 */

const RESULTS_VIEW_DESCRIPTIONS: Record<string, string> = {
    oncoprint:
        'OncoPrint — matrix heatmap showing mutations, CNAs, and structural variants across samples for queried genes.',
    mutations:
        'Lollipop diagram showing protein-level mutation positions, types, and frequencies across samples for queried genes.',
    structuralVariants: 'Structural variant (fusion) table for queried genes.',
    cancerTypesSummary:
        'Alteration frequencies for queried genes broken down by cancer type.',
    mutualExclusivity:
        'Co-occurrence and mutual exclusivity statistics for all queried gene pairs.',
    plots: 'Scatter and box plots comparing two data dimensions — gene vs gene, expression vs CNA, gene vs clinical attribute, etc.',
    survival:
        'Kaplan-Meier survival curves comparing altered vs unaltered sample groups.',
    coexpression:
        'Correlation scatter plots between queried genes and all other genes in the study.',
    comparison:
        'Group comparison (Altered vs Unaltered, or per-gene groups) with clinical, enrichment, and survival subtabs.',
    'comparison/overlap':
        'Venn diagram showing sample overlap between Altered and Unaltered groups.',
    'comparison/survival':
        'Kaplan-Meier survival analysis comparing Altered vs Unaltered groups.',
    'comparison/clinical':
        'Clinical attribute distributions compared between Altered and Unaltered groups.',
    'comparison/mrna':
        'mRNA expression enrichment — genes ranked by differential expression (log ratio, q-value) between Altered and Unaltered groups.',
    'comparison/protein':
        'Protein expression enrichment (RPPA) between Altered and Unaltered groups.',
    'comparison/dna_methylation':
        'DNA methylation enrichment — probes ranked by differential methylation between Altered and Unaltered groups.',
    'comparison/alterations':
        'Mutation and CNA enrichment ranked by q-value between Altered and Unaltered groups.',
    cnSegments:
        'Copy number segment plots across chromosomes (IGV-style) for queried genes.',
    pathways:
        'Pathway mapper showing alteration frequencies for queried genes in pathway context.',
    download:
        'Data export — alteration, clinical, and expression data in tabular format.',
};

const GROUP_COMPARISON_DESCRIPTIONS: Record<string, string> = {
    overlap: 'Venn diagram showing sample and patient overlap between groups.',
    survival:
        'Kaplan-Meier survival curves (OS, PFS, DFS) with log-rank p-values comparing outcomes across groups.',
    clinical:
        'Clinical attribute distributions compared across groups — bar charts, box plots, and statistical tests.',
    alterations:
        'Mutation and copy number alteration enrichment — genes ranked by q-value, with alteration frequencies per group.',
    mutations:
        'Mutation lollipop diagrams comparing protein-level mutation positions and frequencies across groups.',
    mrna: 'mRNA expression enrichment — genes ranked by differential expression (log ratio, q-value) between groups.',
    protein:
        'Protein expression enrichment (RPPA) — same structure as mRNA but for protein-level data.',
    dna_methylation:
        'DNA methylation enrichment — probes ranked by differential methylation across groups.',
};

const PATIENT_VIEW_DESCRIPTIONS: Record<string, string> = {
    summary:
        'Patient overview — clinical event timeline, genomic overview tracks (mutations and CNAs across samples), mutation table, structural variant table, and copy number table.',
    clinicalData:
        'Clinical attribute tables for the patient and their samples, plus a timeline events table.',
    pathways:
        "Pathway mapper showing the patient's mutations and CNAs overlaid on pathway diagrams.",
};

const STUDY_VIEW_DESCRIPTIONS: Record<string, string> = {
    summary:
        'Configurable grid of interactive charts (bar, pie, scatter, survival) for clinical and genomic attributes. Each chart doubles as a filter — clicking selects a sample subset.',
    clinicalData:
        'Paginated table of clinical attribute values per sample. Searchable and sortable; displays up to 500 rows.',
    cnSegments:
        'IGV-style copy number segment viewer for the selected samples (disabled above 20,000 samples).',
    plots: 'Scatter and box plots comparing two data dimensions — clinical attribute vs clinical attribute, gene vs clinical attribute, etc.',
};

const GENERIC_ASSAY_DESCRIPTION =
    'Generic assay enrichment — entities ranked by differential values across groups.';

const GENERIC_ASSAY_TYPE_DESCRIPTIONS: Record<string, string> = {
    armlevel_cna:
        'Chromosome arm-level CNA enrichment — arms ranked by differential gain/loss frequency across groups.',
    methylation:
        'DNA methylation enrichment (HM27/HM450) — probes ranked by differential methylation beta values across groups.',
    genetic_ancestry:
        'Genetic ancestry enrichment — ancestry components (e.g., European, African, East Asian fractions) compared across groups.',
    mutational_signature:
        'Mutational signature enrichment — COSMIC signature exposures ranked by differential activity across groups.',
    phosphoproteome:
        'Phosphoproteomic enrichment — phosphopeptides ranked by differential phosphorylation across groups.',
    phosphosite_quantification:
        'Phosphosite enrichment — specific phosphorylation sites ranked by differential quantification across groups.',
    acetylproteome:
        'Acetylproteomic enrichment — acetylated proteins/peptides ranked by differential acetylation across groups.',
};

export function getPatientViewPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    return PATIENT_VIEW_DESCRIPTIONS[tab];
}

export function getStudyViewPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    return STUDY_VIEW_DESCRIPTIONS[tab];
}

export function getResultsViewPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    return RESULTS_VIEW_DESCRIPTIONS[tab];
}

export function getGroupComparisonPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    if (tab.startsWith('generic_assay_')) {
        const type = tab.slice('generic_assay_'.length);
        return (
            GENERIC_ASSAY_TYPE_DESCRIPTIONS[type] ?? GENERIC_ASSAY_DESCRIPTION
        );
    }
    return GROUP_COMPARISON_DESCRIPTIONS[tab];
}
