/**
 * Curated descriptions of cBioPortal page tabs, used in tool responses
 * to give the LLM accurate context about what each tab shows.
 *
 * These are sourced from the cBioPortal frontend and documentation —
 * NOT generated by the LLM. The LLM is instructed to use this field
 * verbatim and not to supplement it with training-data knowledge.
 */

const RESULTS_VIEW_DESCRIPTIONS: Record<string, string> = {
    oncoprint: 'Visual summary of alterations in queried genes across samples.',
    mutations:
        'Detailed mutation table with lollipop plot showing mutation positions, types, and frequencies for queried genes.',
    structuralVariants: 'Structural variant (fusion) table for queried genes.',
    cancerTypesSummary:
        'Alteration frequencies for queried genes by cancer type.',
    mutualExclusivity:
        'Co-occurrence and mutual exclusivity statistics for all queried gene pairs.',
    plots: 'Scatter/box plots comparing any two data elements.',
    survival:
        'Kaplan-Meier survival curves comparing groups defined by query genes.',
    coexpression:
        'Correlation between expression of each queried gene vs all other genes.',
    comparison:
        'Compare groups of samples defined by query genes across data modalities including clinical, genomic, and survival.',
    'comparison/overlap':
        'Diagram showing sample and patient overlap between groups defined by query genes.',
    'comparison/survival':
        'Kaplan-Meier survival analysis comparing groups defined by query genes.',
    'comparison/clinical':
        'Clinical attribute distributions compared across groups defined by query genes.',
    'comparison/mrna':
        'mRNA expression for all genes compared across groups defined by query genes.',
    'comparison/protein':
        'Protein expression for all genes compared across groups defined by query genes.',
    'comparison/dna_methylation':
        'DNA methylation levels compared across groups defined by query genes.',
    'comparison/alterations':
        'Comparison of rate of genomic alterations (mutations, CNA, structural variants) in all genes compared across groups defined by query genes.',
    cnSegments: 'Copy number segment plots for queried genes.',
    pathways:
        'Pathway enrichment (via PathwayMapper or NDEx) showing alteration frequencies for queried genes.',
    download: 'Download query-associated data in a variety of tabular formats.',
};

const GROUP_COMPARISON_DESCRIPTIONS: Record<string, string> = {
    overlap: 'Diagram showing sample and patient overlap between groups.',
    survival: 'Kaplan-Meier survival analysis comparing groups.',
    clinical: 'Clinical attribute distributions compared across groups.',
    alterations:
        'Comparison of rate of genomic alterations (mutations, CNA, structural variants) in all genes compared across groups.',
    mutations:
        'Comparison of specific mutation (protein change) frequency between two groups.',
    mrna: 'mRNA expression for all genes compared across groups.',
    protein: 'Protein expression for all genes compared across groups.',
    dna_methylation: 'DNA methylation levels compared across groups.',
};

const PATIENT_VIEW_DESCRIPTIONS: Record<string, string> = {
    summary:
        'Patient overview including patient history timeline (if available) and tables of mutations, structural variants, and copy number alterations.',
    clinicalData:
        'Clinical attribute tables for the patient and each associated sample.',
    pathways:
        "PathwayMapper showing the patient's genomic alterations overlaid on pathway diagrams.",
};

const STUDY_VIEW_DESCRIPTIONS: Record<string, string> = {
    summary:
        'Overview of all study data displayed as interactive charts summarizing available clinical and genomic data. Click within a chart to filter. Additional charts may be available in the Charts menu.',
    clinicalData: 'Table of clinical attributes per sample.',
    cnSegments:
        'Genome-wide copy number segments visualized in IGV for the selected samples (disabled above 20,000 samples).',
    plots: 'Scatter/box plots comparing any two data elements.',
};

const GENERIC_ASSAY_DESCRIPTION =
    'Generic assay enrichment — entities ranked by differential values across groups.';

export function getPatientViewPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    return PATIENT_VIEW_DESCRIPTIONS[tab];
}

export function getStudyViewPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    return STUDY_VIEW_DESCRIPTIONS[tab];
}

export function getResultsViewPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    return RESULTS_VIEW_DESCRIPTIONS[tab];
}

export function getGroupComparisonPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    if (tab.startsWith('generic_assay_')) return GENERIC_ASSAY_DESCRIPTION;
    return GROUP_COMPARISON_DESCRIPTIONS[tab];
}
