/**
 * Curated descriptions of cBioPortal page tabs, used in tool responses
 * to give the LLM accurate context about what each tab shows.
 *
 * These are sourced from the cBioPortal frontend and documentation —
 * NOT generated by the LLM. The LLM is instructed to use this field
 * verbatim and not to supplement it with training-data knowledge.
 *
 * Context params allow tools to produce specific descriptions (e.g. axis
 * labels for plots, group names for comparisons) without LLM involvement.
 * Functions fall back to the static string when context is absent.
 */

type PlotsAxisInput = {
    selectedGeneOption?: string;
    dataType?: string;
    selectedDataSourceOption?: string;
};

export type PlotsDescriptionContext = {
    plotsHorz?: PlotsAxisInput;
    plotsVert?: PlotsAxisInput;
};

export type ResultsViewDescriptionContext = PlotsDescriptionContext & {
    comparisonSelectedGroups?: string[];
};

export type GroupComparisonDescriptionContext = {
    groups?: Array<{ name: string; sampleCount?: number }>;
    attributeName?: string;
};

const DATA_TYPE_LABELS: Record<string, string> = {
    MRNA_EXPRESSION: 'mRNA expression',
    MUTATION_EXTENDED: 'mutation',
    COPY_NUMBER_ALTERATION: 'CNA',
    METHYLATION: 'methylation',
    PROTEIN_LEVEL: 'protein expression',
    STRUCTURAL_VARIANT: 'structural variants',
};

function plotsAxisLabel(sel: PlotsAxisInput): string {
    const {
        selectedGeneOption: gene,
        dataType,
        selectedDataSourceOption: source,
    } = sel;
    if (dataType === 'clinical_attribute') {
        return source?.replace(/_/g, ' ').toLowerCase() ?? 'clinical attribute';
    }
    const typeLabel = dataType
        ? (DATA_TYPE_LABELS[dataType] ?? dataType.toLowerCase())
        : 'data';
    return gene ? `${gene} ${typeLabel}` : typeLabel;
}

function buildGroupStr(context: GroupComparisonDescriptionContext): string {
    if (context.attributeName) {
        return `${context.attributeName} groups`;
    }
    if (context.groups?.length) {
        return context.groups
            .map((g) =>
                g.sampleCount !== undefined
                    ? `${g.name} (${g.sampleCount})`
                    : g.name
            )
            .join(' vs ');
    }
    return '';
}

const RESULTS_VIEW_DESCRIPTIONS: Record<string, string> = {
    oncoprint: 'Visual summary of alterations in queried genes across samples.',
    mutations:
        'Detailed mutation table with lollipop plot showing mutation positions, types, and frequencies for queried genes.',
    structuralVariants: 'Structural variant (fusion) table for queried genes.',
    cancerTypesSummary:
        'Alteration frequencies for queried genes by cancer type.',
    mutualExclusivity:
        'Co-occurrence and mutual exclusivity statistics for all queried gene pairs.',
    plots: 'Scatter/box plots comparing any two data elements.',
    survival:
        'Kaplan-Meier survival curves comparing groups defined by query genes.',
    coexpression:
        'Correlation between expression of each queried gene vs all other genes.',
    comparison:
        'Compare groups of samples defined by query genes across data modalities including clinical, genomic, and survival.',
    'comparison/overlap':
        'Diagram showing sample and patient overlap between groups defined by query genes.',
    'comparison/survival':
        'Kaplan-Meier survival analysis comparing groups defined by query genes.',
    'comparison/clinical':
        'Clinical attribute distributions compared across groups defined by query genes.',
    'comparison/mrna':
        'mRNA expression for all genes compared across groups defined by query genes.',
    'comparison/protein':
        'Protein expression for all genes compared across groups defined by query genes.',
    'comparison/dna_methylation':
        'DNA methylation levels compared across groups defined by query genes.',
    'comparison/alterations':
        'Comparison of rate of genomic alterations (mutations, CNA, structural variants) in all genes compared across groups defined by query genes.',
    cnSegments: 'Copy number segment plots for queried genes.',
    pathways:
        'Pathway enrichment (via PathwayMapper or NDEx) showing alteration frequencies for queried genes.',
    download: 'Download query-associated data in a variety of tabular formats.',
};

const GROUP_COMPARISON_DESCRIPTIONS: Record<string, string> = {
    overlap: 'Diagram showing sample and patient overlap between groups.',
    survival: 'Kaplan-Meier survival analysis comparing groups.',
    clinical: 'Clinical attribute distributions compared across groups.',
    alterations:
        'Comparison of rate of genomic alterations (mutations, CNA, structural variants) in all genes compared across groups.',
    mutations:
        'Comparison of specific mutation (protein change) frequency between two groups.',
    mrna: 'mRNA expression for all genes compared across groups.',
    protein: 'Protein expression for all genes compared across groups.',
    dna_methylation: 'DNA methylation levels compared across groups.',
};

const PATIENT_VIEW_DESCRIPTIONS: Record<string, string> = {
    summary:
        'Patient overview including patient history timeline (if available) and tables of mutations, structural variants, and copy number alterations.',
    clinicalData:
        'Clinical attribute tables for the patient and each associated sample.',
    pathways:
        "PathwayMapper showing the patient's genomic alterations overlaid on pathway diagrams.",
};

const STUDY_VIEW_DESCRIPTIONS: Record<string, string> = {
    summary:
        'Overview of all study data displayed as interactive charts summarizing available clinical and genomic data. Click within a chart to filter. Additional charts may be available in the Charts menu.',
    clinicalData: 'Table of clinical attributes per sample.',
    cnSegments:
        'Genome-wide copy number segments visualized in IGV for the selected samples (disabled above 20,000 samples).',
    plots: 'Scatter/box plots comparing any two data elements.',
};

const GENERIC_ASSAY_DESCRIPTION =
    'Generic assay enrichment — entities ranked by differential values across groups.';

const GENERIC_ASSAY_TYPE_DESCRIPTIONS: Record<string, string> = {
    armlevel_cna:
        'Chromosome arm-level CNA enrichment — arms ranked by differential gain/loss frequency across groups.',
    methylation:
        'DNA methylation enrichment (HM27/HM450) — probes ranked by differential methylation beta values across groups.',
    genetic_ancestry:
        'Genetic ancestry enrichment — ancestry components (e.g., European, African, East Asian fractions) compared across groups.',
    mutational_signature:
        'Mutational signature enrichment — COSMIC signature exposures ranked by differential activity across groups.',
    phosphoproteome:
        'Phosphoproteomic enrichment — phosphopeptides ranked by differential phosphorylation across groups.',
    phosphosite_quantification:
        'Phosphosite enrichment — specific phosphorylation sites ranked by differential quantification across groups.',
    acetylproteome:
        'Acetylproteomic enrichment — acetylated proteins/peptides ranked by differential acetylation across groups.',
};

export function getPatientViewPageDescription(
    tab: string | undefined
): string | undefined {
    if (!tab) return undefined;
    return PATIENT_VIEW_DESCRIPTIONS[tab];
}

export function getStudyViewPageDescription(
    tab: string | undefined,
    context?: PlotsDescriptionContext
): string | undefined {
    if (!tab) return undefined;
    if (tab === 'plots' && context?.plotsHorz && context?.plotsVert) {
        const vert = plotsAxisLabel(context.plotsVert);
        const horz = plotsAxisLabel(context.plotsHorz);
        return `Scatter/box plots: ${vert} (y-axis) by ${horz} (x-axis).`;
    }
    return STUDY_VIEW_DESCRIPTIONS[tab];
}

export function getResultsViewPageDescription(
    tab: string | undefined,
    context?: ResultsViewDescriptionContext
): string | undefined {
    if (!tab) return undefined;
    if (tab === 'plots' && context?.plotsHorz && context?.plotsVert) {
        const vert = plotsAxisLabel(context.plotsVert);
        const horz = plotsAxisLabel(context.plotsHorz);
        return `Scatter/box plots: ${vert} (y-axis) by ${horz} (x-axis).`;
    }
    if (
        tab.startsWith('comparison/') &&
        context?.comparisonSelectedGroups?.length
    ) {
        const groupStr = context.comparisonSelectedGroups
            .map((g) => `${g}-altered`)
            .join(' vs ');
        const COMPARISON_DYNAMIC: Record<string, string> = {
            'comparison/overlap': `Diagram showing sample and patient overlap across ${groupStr}.`,
            'comparison/survival': `Kaplan-Meier survival comparing ${groupStr}.`,
            'comparison/clinical': `Clinical attribute distributions compared across ${groupStr}.`,
            'comparison/mrna': `mRNA expression for all genes compared across ${groupStr}.`,
            'comparison/protein': `Protein expression for all genes compared across ${groupStr}.`,
            'comparison/dna_methylation': `DNA methylation levels compared across ${groupStr}.`,
            'comparison/alterations': `Genomic alteration rates compared across ${groupStr}.`,
        };
        return COMPARISON_DYNAMIC[tab] ?? RESULTS_VIEW_DESCRIPTIONS[tab];
    }
    return RESULTS_VIEW_DESCRIPTIONS[tab];
}

export function getGroupComparisonPageDescription(
    tab: string | undefined,
    context?: GroupComparisonDescriptionContext
): string | undefined {
    if (!tab) return undefined;
    if (tab.startsWith('generic_assay_')) {
        const type = tab.slice('generic_assay_'.length);
        return (
            GENERIC_ASSAY_TYPE_DESCRIPTIONS[type] ?? GENERIC_ASSAY_DESCRIPTION
        );
    }
    const base = GROUP_COMPARISON_DESCRIPTIONS[tab];
    if (!base || !context) return base;
    const groupStr = buildGroupStr(context);
    if (!groupStr) return base;
    const DYNAMIC: Record<string, string> = {
        overlap: `Diagram showing sample and patient overlap across ${groupStr}.`,
        survival: `Kaplan-Meier survival analysis comparing ${groupStr}.`,
        clinical: `Clinical attribute distributions compared across ${groupStr}.`,
        alterations: `Comparison of genomic alteration rates across ${groupStr}.`,
        mutations: `Mutation frequency (protein change) compared across ${groupStr}.`,
        mrna: `mRNA expression for all genes compared across ${groupStr}.`,
        protein: `Protein expression for all genes compared across ${groupStr}.`,
        dna_methylation: `DNA methylation levels compared across ${groupStr}.`,
    };
    return DYNAMIC[tab] ?? base;
}
