// Generated by ts-to-zod
import { z } from 'zod';

export const alterationCountByGeneSchema = z.object({
    entrezGeneId: z.number(),
    entrezGeneIds: z.array(z.number()),
    hugoGeneSymbol: z.string(),
    hugoGeneSymbols: z.array(z.string()),
    matchingGenePanelIds: z.array(z.string()),
    numberOfAlteredCases: z.number(),
    numberOfProfiledCases: z.number(),
    qValue: z.number(),
    totalCount: z.number(),
    uniqueEventKey: z.string(),
});

export const alterationCountByStructuralVariantSchema = z.object({
    entrezGeneIds: z.array(z.number()),
    gene1EntrezGeneId: z.number(),
    gene1HugoGeneSymbol: z.string(),
    gene2EntrezGeneId: z.number(),
    gene2HugoGeneSymbol: z.string(),
    hugoGeneSymbols: z.array(z.string()),
    matchingGenePanelIds: z.array(z.string()),
    numberOfAlteredCases: z.number(),
    numberOfProfiledCases: z.number(),
    totalCount: z.number(),
    uniqueEventKey: z.string(),
});

export const countSummarySchema = z.object({
    alteredCount: z.number(),
    name: z.string(),
    profiledCount: z.number(),
});

export const alterationFilterSchema = z.object({
    copyNumberAlterationEventTypes: z.object({}),
    includeDriver: z.boolean(),
    includeGermline: z.boolean(),
    includeSomatic: z.boolean(),
    includeUnknownOncogenicity: z.boolean(),
    includeUnknownStatus: z.boolean(),
    includeUnknownTier: z.boolean(),
    includeVUS: z.boolean(),
    mutationEventTypes: z.object({}),
    structuralVariants: z.boolean(),
    tiersBooleanMap: z.object({}),
});

export const binsGeneratorConfigSchema = z.object({
    anchorValue: z.number(),
    binSize: z.number(),
});

export const caseListDataCountSchema = z.object({
    count: z.number(),
    label: z.string(),
    value: z.string(),
});

export const clinicalAttributeSchema = z.object({
    clinicalAttributeId: z.string(),
    datatype: z.string(),
    description: z.string(),
    displayName: z.string(),
    patientAttribute: z.boolean(),
    priority: z.string(),
    studyId: z.string(),
});

export const clinicalAttributeCountSchema = z.object({
    clinicalAttributeId: z.string(),
    count: z.number(),
});

export const sampleIdentifierSchema = z.object({
    sampleId: z.string(),
    studyId: z.string(),
});

export const clinicalDataSchema = z.object({
    clinicalAttribute: clinicalAttributeSchema,
    clinicalAttributeId: z.string(),
    patientAttribute: z.boolean(),
    patientId: z.string(),
    sampleId: z.string(),
    studyId: z.string(),
    uniquePatientKey: z.string(),
    uniqueSampleKey: z.string(),
    value: z.string(),
});

export const clinicalDataBinSchema = z.object({
    attributeId: z.string(),
    count: z.number(),
    end: z.number(),
    specialValue: z.string(),
    start: z.number(),
});

export const clinicalDataBinFilterSchema = z.object({
    attributeId: z.string(),
    binMethod: z.union([
        z.literal('MEDIAN'),
        z.literal('QUARTILE'),
        z.literal('CUSTOM'),
        z.literal('GENERATE'),
    ]),
    binsGeneratorConfig: binsGeneratorConfigSchema,
    customBins: z.array(z.number()),
    disableLogScale: z.boolean(),
    end: z.number(),
    start: z.number(),
});

export const clinicalDataCountSchema = z.object({
    count: z.number(),
    value: z.string(),
});

export const clinicalDataCountItemSchema = z.object({
    attributeId: z.string(),
    counts: z.array(clinicalDataCountSchema),
});

export const clinicalDataEnrichmentSchema = z.object({
    clinicalAttribute: clinicalAttributeSchema,
    method: z.string(),
    pValue: z.number(),
    score: z.number(),
});

export const dataFilterValueSchema = z.object({
    end: z.number(),
    start: z.number(),
    value: z.string(),
});

export const clinicalEventDataSchema = z.object({
    key: z.string(),
    value: z.string(),
});

export const clinicalEventRequestSchema = z.object({
    attributes: z.array(clinicalEventDataSchema),
    eventType: z.string(),
});

export const patientIdentifierSchema = z.object({
    patientId: z.string(),
    studyId: z.string(),
});

export const clinicalEventRequestIdentifierSchema = z.object({
    clinicalEventRequests: z.array(clinicalEventRequestSchema),
    position: z.union([z.literal('FIRST'), z.literal('LAST')]),
});

export const clinicalEventSampleSchema = z.object({
    patientId: z.string(),
    sampleId: z.string(),
    studyId: z.string(),
    timeTaken: z.number(),
});

export const clinicalEventTypeCountSchema = z.object({
    count: z.number(),
    eventType: z.string(),
});

export const clinicalViolinPlotBoxDataSchema = z.object({
    median: z.number(),
    q1: z.number(),
    q3: z.number(),
    whiskerLower: z.number(),
    whiskerUpper: z.number(),
});

export const clinicalViolinPlotIndividualPointSchema = z.object({
    sampleId: z.string(),
    studyId: z.string(),
    value: z.number(),
});

export const clinicalViolinPlotRowDataSchema = z.object({
    boxData: clinicalViolinPlotBoxDataSchema,
    category: z.string(),
    curveData: z.array(z.number()),
    individualPoints: z.array(clinicalViolinPlotIndividualPointSchema),
    numSamples: z.number(),
});

export const coExpressionSchema = z.object({
    geneticEntityId: z.string(),
    geneticEntityType: z.union([
        z.literal('GENE'),
        z.literal('GENESET'),
        z.literal('PHOSPHOPROTEIN'),
        z.literal('GENERIC_ASSAY'),
    ]),
    pValue: z.number(),
    spearmansCorrelation: z.number(),
});

export const coExpressionFilterSchema = z.object({
    entrezGeneId: z.number(),
    genesetId: z.string(),
    sampleIds: z.array(z.string()),
    sampleListId: z.string(),
});

export const copyNumberCountSchema = z.object({
    alteration: z.number(),
    entrezGeneId: z.number(),
    molecularProfileId: z.string(),
    numberOfSamples: z.number(),
    numberOfSamplesWithAlterationInGene: z.number(),
});

export const copyNumberCountByGeneSchema = z.object({
    alteration: z.number(),
    cytoband: z.string(),
    entrezGeneId: z.number(),
    entrezGeneIds: z.array(z.number()),
    hugoGeneSymbol: z.string(),
    hugoGeneSymbols: z.array(z.string()),
    matchingGenePanelIds: z.array(z.string()),
    numberOfAlteredCases: z.number(),
    numberOfProfiledCases: z.number(),
    qValue: z.number(),
    totalCount: z.number(),
    uniqueEventKey: z.string(),
});

export const copyNumberCountIdentifierSchema = z.object({
    alteration: z.number(),
    entrezGeneId: z.number(),
});

export const cosmicMutationSchema = z.object({
    cosmicMutationId: z.string(),
    count: z.number(),
    keyword: z.string(),
    proteinChange: z.string(),
});

export const customDriverAnnotationReportSchema = z.object({
    hasBinary: z.boolean(),
    tiers: z.array(z.string()),
});

export const dataAccessTokenSchema = z.object({
    creation: z.string(),
    expiration: z.string(),
    token: z.string(),
    username: z.string(),
});

export const dataFilterSchema = z.object({
    values: z.array(dataFilterValueSchema),
});

export const densityPlotBinSchema = z.object({
    binX: z.number(),
    binY: z.number(),
    count: z.number(),
    maxX: z.number(),
    maxY: z.number(),
    minX: z.number(),
    minY: z.number(),
});

export const densityPlotDataSchema = z.object({
    bins: z.array(densityPlotBinSchema),
    pearsonCorr: z.number(),
    spearmanCorr: z.number(),
});

export const geneFilterQuerySchema = z.object({
    alterations: z.array(
        z.union([
            z.literal('AMP'),
            z.literal('GAIN'),
            z.literal('DIPLOID'),
            z.literal('HETLOSS'),
            z.literal('HOMDEL'),
        ])
    ),
    entrezGeneId: z.number(),
    hugoGeneSymbol: z.string(),
    includeDriver: z.boolean(),
    includeGermline: z.boolean(),
    includeSomatic: z.boolean(),
    includeUnknownOncogenicity: z.boolean(),
    includeUnknownStatus: z.boolean(),
    includeUnknownTier: z.boolean(),
    includeVUS: z.boolean(),
    tiersBooleanMap: z.object({}),
});

export const genericAssayCountSummarySchema = z.object({
    count: z.number(),
    name: z.string(),
    totalCount: z.number(),
});

export const groupStatisticsSchema = z.object({
    meanExpression: z.number(),
    name: z.string(),
    standardDeviation: z.number(),
});

export const genericAssayCategoricalEnrichmentSchema = z.object({
    genericEntityMetaProperties: z.object({}),
    groupsStatistics: z.array(groupStatisticsSchema),
    name: z.string(),
    pValue: z.number(),
    qValue: z.number(),
    stableId: z.string(),
});

export const genericAssayDataBinSchema = z.object({
    count: z.number(),
    end: z.number(),
    profileType: z.string(),
    specialValue: z.string(),
    stableId: z.string(),
    start: z.number(),
});

export const genericAssayDataBinFilterSchema = z.object({
    binMethod: z.union([
        z.literal('MEDIAN'),
        z.literal('QUARTILE'),
        z.literal('CUSTOM'),
        z.literal('GENERATE'),
    ]),
    binsGeneratorConfig: binsGeneratorConfigSchema,
    customBins: z.array(z.number()),
    disableLogScale: z.boolean(),
    end: z.number(),
    profileType: z.string(),
    stableId: z.string(),
    start: z.number(),
});

export const genericAssayDataCountSchema = z.object({
    count: z.number(),
    value: z.string(),
});

export const genericAssayDataFilterSchema = z.object({
    profileType: z.string(),
    stableId: z.string(),
    values: z.array(dataFilterValueSchema),
});

export const genericAssayDataCountItemSchema = z.object({
    counts: z.array(genericAssayDataCountSchema),
    stableId: z.string(),
});

export const genericAssayEnrichmentSchema = z.object({
    genericEntityMetaProperties: z.object({}),
    groupsStatistics: z.array(groupStatisticsSchema),
    name: z.string(),
    pValue: z.number(),
    qValue: z.number(),
    stableId: z.string(),
});

export const genesetSchema = z.object({
    description: z.string(),
    genesetId: z.string(),
    name: z.string(),
    refLink: z.string(),
    representativePvalue: z.number(),
    representativeScore: z.number(),
});

export const genesetCorrelationSchema = z.object({
    correlationValue: z.number(),
    entrezGeneId: z.number(),
    expressionGeneticProfileId: z.string(),
    hugoGeneSymbol: z.string(),
    zScoreGeneticProfileId: z.string(),
});

export const genesetDataFilterCriteriaSchema = z.object({
    genesetIds: z.array(z.string()),
    sampleIds: z.array(z.string()),
    sampleListId: z.string(),
});

export const genesetHierarchyInfoSchema = z.object({
    genesets: z.array(genesetSchema),
    nodeId: z.number(),
    nodeName: z.string(),
    parentId: z.number(),
    parentNodeName: z.string(),
});

export const genesetMolecularDataSchema = z.object({
    geneset: genesetSchema,
    genesetId: z.string(),
    geneticProfileId: z.string(),
    patientId: z.string(),
    sampleId: z.string(),
    stableId: z.string(),
    studyId: z.string(),
    uniquePatientKey: z.string(),
    uniqueSampleKey: z.string(),
    value: z.string(),
});

export const genomicDataBinSchema = z.object({
    count: z.number(),
    end: z.number(),
    hugoGeneSymbol: z.string(),
    profileType: z.string(),
    specialValue: z.string(),
    start: z.number(),
});

export const genomicDataBinFilterSchema = z.object({
    binMethod: z.union([
        z.literal('MEDIAN'),
        z.literal('QUARTILE'),
        z.literal('CUSTOM'),
        z.literal('GENERATE'),
    ]),
    binsGeneratorConfig: binsGeneratorConfigSchema,
    customBins: z.array(z.number()),
    disableLogScale: z.boolean(),
    end: z.number(),
    hugoGeneSymbol: z.string(),
    profileType: z.string(),
    start: z.number(),
});

export const genomicDataCountSchema = z.object({
    count: z.number(),
    label: z.string(),
    uniqueCount: z.number(),
    value: z.string(),
});

export const genomicDataFilterSchema = z.object({
    hugoGeneSymbol: z.string(),
    profileType: z.string(),
    values: z.array(dataFilterValueSchema),
});

export const genomicDataCountItemSchema = z.object({
    counts: z.array(genomicDataCountSchema),
    hugoGeneSymbol: z.string(),
    profileType: z.string(),
});

export const genomicEnrichmentSchema = z.object({
    cytoband: z.string(),
    entrezGeneId: z.number(),
    groupsStatistics: z.array(groupStatisticsSchema),
    hugoGeneSymbol: z.string(),
    pValue: z.number(),
});

export const gisticToGeneSchema = z.object({
    entrezGeneId: z.number(),
    hugoGeneSymbol: z.string(),
});

export const groupSchema = z.object({
    name: z.string(),
    sampleIdentifiers: z.array(sampleIdentifierSchema),
});

export const groupFilterSchema = z.object({
    groups: z.array(groupSchema),
});

export const molecularProfileCaseIdentifierSchema = z.object({
    caseId: z.string(),
    molecularProfileId: z.string(),
});

export const molecularProfileCasesGroupFilterSchema = z.object({
    molecularProfileCaseIdentifiers: z.array(
        molecularProfileCaseIdentifierSchema
    ),
    name: z.string(),
});

export const mrnaPercentileSchema = z.object({
    entrezGeneId: z.number(),
    molecularProfileId: z.string(),
    patientId: z.string(),
    percentile: z.number(),
    sampleId: z.string(),
    studyId: z.string(),
    uniquePatientKey: z.string(),
    uniqueSampleKey: z.string(),
    zScore: z.number(),
});

export const mutSigSchema = z.object({
    entrezGeneId: z.number(),
    hugoGeneSymbol: z.string(),
    numberOfMutations: z.number(),
    pValue: z.number(),
    qValue: z.number(),
    rank: z.number(),
    studyId: z.string(),
});

export const mutationCountByPositionSchema = z.object({
    count: z.number(),
    entrezGeneId: z.number(),
    proteinPosEnd: z.number(),
    proteinPosStart: z.number(),
});

export const mutationDataFilterSchema = z.object({
    categorization: z.union([z.literal('MUTATED'), z.literal('MUTATION_TYPE')]),
    hugoGeneSymbol: z.string(),
    profileType: z.string(),
    values: z.array(z.array(dataFilterValueSchema)),
});

export const mutationPositionIdentifierSchema = z.object({
    entrezGeneId: z.number(),
    proteinPosEnd: z.number(),
    proteinPosStart: z.number(),
});

export const mutationSpectrumSchema = z.object({
    CtoA: z.number(),
    CtoG: z.number(),
    CtoT: z.number(),
    TtoA: z.number(),
    TtoC: z.number(),
    TtoG: z.number(),
    molecularProfileId: z.string(),
    patientId: z.string(),
    sampleId: z.string(),
    studyId: z.string(),
    uniquePatientKey: z.string(),
    uniqueSampleKey: z.string(),
});

export const mutationSpectrumFilterSchema = z.object({
    sampleIds: z.array(z.string()),
    sampleListId: z.string(),
});

export const namespaceAttributeCountSchema = z.object({
    outerKey: z.string(),
    innerKey: z.string(),
    count: z.number(),
});

export const namespaceAttributeSchema = z.object({
    innerKey: z.string(),
    outerKey: z.string(),
});

export const namespaceComparisonFilterSchema = z.object({
    sampleIdentifiers: z.array(sampleIdentifierSchema),
    namespaceAttribute: namespaceAttributeSchema,
    values: z.array(z.string()),
});

export const namespaceDataSchema = z.object({
    outerKey: z.string(),
    innerKey: z.string(),
    sampleId: z.string(),
    patientId: z.string(),
    studyId: z.string(),
    attrValue: z.array(z.string()),
});

export const namespaceDataCountSchema = z.object({
    count: z.number(),
    value: z.string(),
    totalCount: z.number(),
});

export const namespaceDataFilterSchema = z.object({
    outerKey: z.string(),
    innerKey: z.string(),
    values: z.array(z.array(dataFilterValueSchema)),
});

export const namespaceDataCountItemSchema = z.object({
    outerKey: z.string(),
    innerKey: z.string(),
    counts: z.array(namespaceDataCountSchema),
});

export const patientTreatmentFilterSchema = z.object({
    treatment: z.string(),
});

export const sampleTreatmentFilterSchema = z.object({
    time: z.union([z.literal('Pre'), z.literal('Post')]),
    treatment: z.string(),
});

export const patientTreatmentSchema = z.object({
    count: z.number(),
    treatment: z.string(),
});

export const patientTreatmentReportSchema = z.object({
    patientTreatments: z.array(patientTreatmentSchema),
    totalPatients: z.number(),
    totalSamples: z.number(),
});

export const patientTreatmentRowSchema = z.object({
    count: z.number(),
    samples: z.array(clinicalEventSampleSchema),
    treatment: z.string(),
});

export const referenceGenomeGeneSchema = z.object({
    chromosome: z.string(),
    cytoband: z.string(),
    end: z.number(),
    entrezGeneId: z.number(),
    hugoGeneSymbol: z.string(),
    referenceGenomeId: z.number(),
    start: z.number(),
});

export const resourceDefinitionSchema = z.object({
    description: z.string(),
    displayName: z.string(),
    openByDefault: z.boolean(),
    priority: z.string(),
    resourceId: z.string(),
    resourceType: z.union([
        z.literal('STUDY'),
        z.literal('SAMPLE'),
        z.literal('PATIENT'),
    ]),
    studyId: z.string(),
});

export const sampleSchema = z.object({
    copyNumberSegmentPresent: z.boolean(),
    patientId: z.string(),
    sampleId: z.string(),
    sampleType: z.union([
        z.literal('Primary Solid Tumor'),
        z.literal('Recurrent Solid Tumor'),
        z.literal('Primary Blood Tumor'),
        z.literal('Recurrent Blood Tumor'),
        z.literal('Metastatic'),
        z.literal('Blood Derived Normal'),
        z.literal('Solid Tissues Normal'),
    ]),
    sequenced: z.boolean(),
    studyId: z.string(),
    uniquePatientKey: z.string(),
    uniqueSampleKey: z.string(),
});

export const sampleClinicalDataCollectionSchema = z.object({
    byUniqueSampleKey: z.object({}),
});

export const sampleMolecularIdentifierSchema = z.object({
    molecularProfileId: z.string(),
    sampleId: z.string(),
});

export const sampleTreatmentRowSchema = z.object({
    count: z.number(),
    samples: z.array(clinicalEventSampleSchema),
    time: z.union([z.literal('Pre'), z.literal('Post')]),
    treatment: z.string(),
});

export const structuralVariantSchema = z.object({
    annotation: z.string(),
    breakpointType: z.string(),
    comments: z.string(),
    connectionType: z.string(),
    dnaSupport: z.string(),
    driverFilter: z.string(),
    driverFilterAnn: z.string(),
    driverTiersFilter: z.string(),
    driverTiersFilterAnn: z.string(),
    eventInfo: z.string(),
    length: z.number(),
    molecularProfileId: z.string(),
    namespaceColumns: z.object({}),
    ncbiBuild: z.string(),
    normalPairedEndReadCount: z.number(),
    normalReadCount: z.number(),
    normalSplitReadCount: z.number(),
    normalVariantCount: z.number(),
    patientId: z.string(),
    rnaSupport: z.string(),
    sampleId: z.string(),
    site1Chromosome: z.string(),
    site1Contig: z.string(),
    site1Description: z.string(),
    site1EnsemblTranscriptId: z.string(),
    site1EntrezGeneId: z.number(),
    site1HugoSymbol: z.string(),
    site1Position: z.number(),
    site1Region: z.string(),
    site1RegionNumber: z.number(),
    site2Chromosome: z.string(),
    site2Contig: z.string(),
    site2Description: z.string(),
    site2EffectOnFrame: z.string(),
    site2EnsemblTranscriptId: z.string(),
    site2EntrezGeneId: z.number(),
    site2HugoSymbol: z.string(),
    site2Position: z.number(),
    site2Region: z.string(),
    site2RegionNumber: z.number(),
    studyId: z.string(),
    svStatus: z.string(),
    tumorPairedEndReadCount: z.number(),
    tumorReadCount: z.number(),
    tumorSplitReadCount: z.number(),
    tumorVariantCount: z.number(),
    uniquePatientKey: z.string(),
    uniqueSampleKey: z.string(),
    variantClass: z.string(),
});

export const structuralVariantGeneSubQuerySchema = z.object({
    entrezId: z.number(),
    hugoSymbol: z.string(),
    specialValue: z.union([z.literal('ANY_GENE'), z.literal('NO_GENE')]),
});

export const structuralVariantQuerySchema = z.object({
    gene1: structuralVariantGeneSubQuerySchema,
    gene2: structuralVariantGeneSubQuerySchema,
});

export const clinicalDataFilterSchema = z.object({
    attributeId: z.string(),
    values: z.array(dataFilterValueSchema),
});

export const geneFilterSchema = z.object({
    geneQueries: z.array(z.array(geneFilterQuerySchema)),
    molecularProfileIds: z.array(z.string()),
});

export const structuralVariantFilterQuerySchema = z.object({
    gene1Query: structuralVariantGeneSubQuerySchema,
    gene2Query: structuralVariantGeneSubQuerySchema,
    includeDriver: z.boolean(),
    includeGermline: z.boolean(),
    includeSomatic: z.boolean(),
    includeUnknownOncogenicity: z.boolean(),
    includeUnknownStatus: z.boolean(),
    includeUnknownTier: z.boolean(),
    includeVUS: z.boolean(),
    tiersBooleanMap: z.object({}),
});

export const survivalRequestSchema = z.object({
    attributeIdPrefix: z.string(),
    censoredEventRequestIdentifier: clinicalEventRequestIdentifierSchema,
    endEventRequestIdentifier: clinicalEventRequestIdentifierSchema,
    patientIdentifiers: z.array(patientIdentifierSchema),
    startEventRequestIdentifier: clinicalEventRequestIdentifierSchema,
});

export const variantCountSchema = z.object({
    entrezGeneId: z.number(),
    keyword: z.string(),
    molecularProfileId: z.string(),
    numberOfSamples: z.number(),
    numberOfSamplesWithKeyword: z.number(),
    numberOfSamplesWithMutationInGene: z.number(),
});

export const variantCountIdentifierSchema = z.object({
    entrezGeneId: z.number(),
    keyword: z.string(),
});

export const alterationEnrichmentSchema = z.object({
    counts: z.array(countSummarySchema),
    cytoband: z.string(),
    entrezGeneId: z.number(),
    hugoGeneSymbol: z.string(),
    pValue: z.number(),
});

export const oredPatientTreatmentFiltersSchema = z.object({
    filters: z.array(patientTreatmentFilterSchema),
});

export const oredSampleTreatmentFiltersSchema = z.object({
    filters: z.array(sampleTreatmentFilterSchema),
});

export const clinicalAttributeCountFilterSchema = z.object({
    sampleIdentifiers: z.array(sampleIdentifierSchema),
    sampleListId: z.string(),
});

export const clinicalEventSchema = z.object({
    attributes: z.array(clinicalEventDataSchema),
    endNumberOfDaysSinceDiagnosis: z.number(),
    eventType: z.string(),
    patientId: z.string(),
    startNumberOfDaysSinceDiagnosis: z.number(),
    studyId: z.string(),
    uniquePatientKey: z.string(),
    uniqueSampleKey: z.string(),
});

export const clinicalEventAttributeRequestSchema = z.object({
    clinicalEventRequests: z.array(clinicalEventRequestSchema),
    patientIdentifiers: z.array(patientIdentifierSchema),
});

export const clinicalViolinPlotDataSchema = z.object({
    axisEnd: z.number(),
    axisStart: z.number(),
    rows: z.array(clinicalViolinPlotRowDataSchema),
});

export const genericAssayBinaryEnrichmentSchema = z.object({
    counts: z.array(genericAssayCountSummarySchema),
    genericEntityMetaProperties: z.object({}),
    groupsStatistics: z.array(groupStatisticsSchema),
    name: z.string(),
    pValue: z.number(),
    qValue: z.number(),
    stableId: z.string(),
});

export const gisticSchema = z.object({
    amp: z.boolean(),
    chromosome: z.number(),
    cytoband: z.string(),
    genes: z.array(gisticToGeneSchema),
    qValue: z.number(),
    studyId: z.string(),
    widePeakEnd: z.number(),
    widePeakStart: z.number(),
});

export const molecularProfileCasesGroupAndAlterationTypeFilterSchema = z.object(
    {
        alterationEventTypes: alterationFilterSchema,
        molecularProfileCasesGroupFilter: z.array(
            molecularProfileCasesGroupFilterSchema
        ),
    }
);

export const namespaceAttributeCountFilterSchema = z.object({
    sampleIdentifiers: z.array(sampleIdentifierSchema),
    namespaceAttributes: z.array(namespaceAttributeSchema),
});

export const resourceDataSchema = z.object({
    patientId: z.string(),
    resourceDefinition: resourceDefinitionSchema,
    resourceId: z.string(),
    sampleId: z.string(),
    studyId: z.string(),
    uniquePatientKey: z.string(),
    uniqueSampleKey: z.string(),
    url: z.string(),
});

export const sampleTreatmentReportSchema = z.object({
    totalSamples: z.number(),
    treatments: z.array(sampleTreatmentRowSchema),
});

export const structuralVariantFilterSchema = z.object({
    entrezGeneIds: z.array(z.number()),
    molecularProfileIds: z.array(z.string()),
    sampleMolecularIdentifiers: z.array(sampleMolecularIdentifierSchema),
    structuralVariantQueries: z.array(structuralVariantQuerySchema),
});

export const andedPatientTreatmentFiltersSchema = z.object({
    filters: z.array(oredPatientTreatmentFiltersSchema),
});

export const andedSampleTreatmentFiltersSchema = z.object({
    filters: z.array(oredSampleTreatmentFiltersSchema),
});

export const studyViewStructuralVariantFilterSchema = z.object({
    molecularProfileIds: z.array(z.string()),
    structVarQueries: z.array(z.array(structuralVariantFilterQuerySchema)),
});

export const studyViewFilterSchema = z.object({
    alterationFilter: alterationFilterSchema,
    caseLists: z.array(z.array(z.string())),
    clinicalDataFilters: z.array(clinicalDataFilterSchema),
    clinicalEventFilters: z.array(dataFilterSchema),
    customDataFilters: z.array(clinicalDataFilterSchema),
    geneFilters: z.array(geneFilterSchema),
    genericAssayDataFilters: z.array(genericAssayDataFilterSchema),
    genomicDataFilters: z.array(genomicDataFilterSchema),
    genomicProfiles: z.array(z.array(z.string())),
    mutationDataFilters: z.array(mutationDataFilterSchema),
    namespaceDataFilters: z.array(namespaceDataFilterSchema),
    patientTreatmentFilters: andedPatientTreatmentFiltersSchema,
    patientTreatmentGroupFilters: andedPatientTreatmentFiltersSchema,
    patientTreatmentTargetFilters: andedPatientTreatmentFiltersSchema,
    sampleIdentifiers: z.array(sampleIdentifierSchema),
    sampleTreatmentFilters: andedSampleTreatmentFiltersSchema,
    sampleTreatmentGroupFilters: andedSampleTreatmentFiltersSchema,
    sampleTreatmentTargetFilters: andedSampleTreatmentFiltersSchema,
    structuralVariantFilters: z.array(studyViewStructuralVariantFilterSchema),
    studyIds: z.array(z.string()),
});

export const clinicalDataCountFilterSchema = z.object({
    attributes: z.array(clinicalDataFilterSchema),
    studyViewFilter: studyViewFilterSchema,
});

export const genericAssayDataBinCountFilterSchema = z.object({
    genericAssayDataBinFilters: z.array(genericAssayDataBinFilterSchema),
    studyViewFilter: studyViewFilterSchema,
});

export const genericAssayDataCountFilterSchema = z.object({
    genericAssayDataFilters: z.array(genericAssayDataFilterSchema),
    studyViewFilter: studyViewFilterSchema,
});

export const genomicDataBinCountFilterSchema = z.object({
    genomicDataBinFilters: z.array(genomicDataBinFilterSchema),
    studyViewFilter: studyViewFilterSchema,
});

export const genomicDataCountFilterSchema = z.object({
    genomicDataFilters: z.array(genomicDataFilterSchema),
    studyViewFilter: studyViewFilterSchema,
});

export const namespaceDataCountFilterSchema = z.object({
    attributes: z.array(namespaceDataFilterSchema),
    studyViewFilter: studyViewFilterSchema,
});

export const clinicalDataBinCountFilterSchema = z.object({
    attributes: z.array(clinicalDataBinFilterSchema),
    studyViewFilter: studyViewFilterSchema,
});
